apiVersion: batch/v1
kind: Job
metadata:
  name: JOB_NAME
  namespace: free-service
spec:
  template:
    spec:
      containers:
      - name: free-tier-job
        image: mohassan99/free-tier-job:latest
        env:
        - name: DATASET
          value: "mnist"
        - name: TYPE
          value: "ff"
      restartPolicy: Never
  backoffLimit: 0
